# Generated by Django 3.2.6 on 2021-11-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_newsprise_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
